USE dxc_test;


INSERT INTO author (name, birthday) VALUES ('Covey, Stephen R.',STR_TO_DATE('01-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('McConnell, Steve *',STR_TO_DATE('02-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Marcus Aurelius',STR_TO_DATE('03-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Ries, Al',STR_TO_DATE('04-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Covey, Stephen R.',STR_TO_DATE('05-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Graham, Paul',STR_TO_DATE('06-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Drucker, Peter F.',STR_TO_DATE('07-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Signals, 37',STR_TO_DATE('08-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Livingston, Jessica',STR_TO_DATE('09-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Lao Tzu',STR_TO_DATE('10-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Collins, James C.',STR_TO_DATE('11-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Godin, Seth',STR_TO_DATE('12-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Liker, Jeffrey K.',STR_TO_DATE('13-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Bennis, Warren',STR_TO_DATE('14-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Branson, Richard',STR_TO_DATE('15-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('McCormick, Jim',STR_TO_DATE('16-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Grove, Andrew S.',STR_TO_DATE('17-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Maxwell, John C.',STR_TO_DATE('18-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('O''Kelly, Eugene',STR_TO_DATE('19-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Blank, Steve',STR_TO_DATE('20-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Blanchard, Kenneth H. *',STR_TO_DATE('21-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Welch, Jack',STR_TO_DATE('22-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Peter, Laurence J.',STR_TO_DATE('23-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Gamma, Erich',STR_TO_DATE('24-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Gates, Bill *',STR_TO_DATE('25-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Kim, W. Chan *',STR_TO_DATE('26-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Ferriss, Timothy *',STR_TO_DATE('27-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Robbins, Tony',STR_TO_DATE('28-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Saint-Exupéry, Antoine de',STR_TO_DATE('29-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Carnegie, Dale',STR_TO_DATE('30-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Sun Tzu',STR_TO_DATE('31-Jan-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Johnson, Spencer',STR_TO_DATE('01-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Pausch, Randy',STR_TO_DATE('02-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Gladwell, Malcolm',STR_TO_DATE('03-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Kiyosaki, Robert T.',STR_TO_DATE('04-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Godin, Seth',STR_TO_DATE('05-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Knight, Phil',STR_TO_DATE('06-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Gelsinger, Pat',STR_TO_DATE('07-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Benioff, Marc',STR_TO_DATE('08-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Fried, Jason',STR_TO_DATE('09-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Hsieh, Tony',STR_TO_DATE('10-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Sinek, Simon *',STR_TO_DATE('11-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Ries, Eric *',STR_TO_DATE('12-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Isaacson, Walter *',STR_TO_DATE('13-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('蔡康永',STR_TO_DATE('14-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Sivers, Derek *',STR_TO_DATE('15-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('陶晶瑩',STR_TO_DATE('16-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Duhigg, Charles *',STR_TO_DATE('17-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Harari, Yuval Noah',STR_TO_DATE('18-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Inamori, Kazuo',STR_TO_DATE('19-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Sandberg, Sheryl',STR_TO_DATE('20-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Marquet, L. David *',STR_TO_DATE('21-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Hansson, David Heinemeier',STR_TO_DATE('22-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Thiel, Peter',STR_TO_DATE('23-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Horowitz, Ben*',STR_TO_DATE('24-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Eyal, Nir *',STR_TO_DATE('25-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Kishimi, Ichiro',STR_TO_DATE('26-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Livingston, Jessica',STR_TO_DATE('27-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Langelett, George *',STR_TO_DATE('28-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('蔡康永',STR_TO_DATE('29-Feb-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Vance, Ashlee *',STR_TO_DATE('01-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Schmidt, Eric',STR_TO_DATE('02-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('蔡康永;兔斯基团队, Cai Kangyong;Tusiji',STR_TO_DATE('03-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Tett, Gillian',STR_TO_DATE('04-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Wooden, John',STR_TO_DATE('05-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Harari, Yuval Noah',STR_TO_DATE('06-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Voss, Chris *',STR_TO_DATE('07-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Manson, Mark*',STR_TO_DATE('08-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Peterson, Jordan B.',STR_TO_DATE('09-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Sandberg, Sheryl',STR_TO_DATE('10-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Harvard Business Review',STR_TO_DATE('11-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('马薇薇;黄执中;周玄毅, Ma Weiwei;Huang Zh',STR_TO_DATE('12-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Pecaut, Daniel*',STR_TO_DATE('13-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Doerr, John E.',STR_TO_DATE('14-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Cho, Nam-Joo',STR_TO_DATE('15-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Flanders, Cait *',STR_TO_DATE('16-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Harari, Yuval Noah',STR_TO_DATE('17-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Sharma, Robin S.',STR_TO_DATE('18-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Hoffman, Reid*',STR_TO_DATE('19-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Zhuo, Julie *',STR_TO_DATE('20-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Fried, Jason',STR_TO_DATE('21-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Kondo, Marie *',STR_TO_DATE('22-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Clear, James *',STR_TO_DATE('23-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Hawking, Stephen',STR_TO_DATE('24-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('蔡康永',STR_TO_DATE('25-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Iger, Robert',STR_TO_DATE('26-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Eyal, Nir *',STR_TO_DATE('27-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Singer, Ryan',STR_TO_DATE('28-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Levy, Steven *',STR_TO_DATE('29-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Hastings, Reed',STR_TO_DATE('30-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('蔡康永',STR_TO_DATE('31-Mar-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Lasak, Jakub *',STR_TO_DATE('01-Apr-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('马薇薇',STR_TO_DATE('02-Apr-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Yoshino, Genzaburo',STR_TO_DATE('03-Apr-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Bezos, Jeff',STR_TO_DATE('04-Apr-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('六毫子',STR_TO_DATE('05-Apr-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Larson, Will *',STR_TO_DATE('06-Apr-1940','%d-%M-%Y'));
INSERT INTO author (name, birthday) VALUES ('Nooyi, Indra *',STR_TO_DATE('07-Apr-1940','%d-%M-%Y'));

COMMIT;
